# SPDX-FileCopyrightText: 2022-2026 Jonathan A. Thomason <contact@jonathan-thomason.com>
# SPDX-License-Identifier: CC0-1.0

edition = "2024"

hard_tabs = true
newline_style = "Unix"
reorder_imports = true
reorder_modules = true
use_small_heuristics = "Default"
use_try_shorthand = true
imports_layout = "Vertical"
